# This builds Kubernetes on Docker's container engine
# From what I have read, Docker and Podman are mostly interchangeable (I want to learn how wrong that it) and Podman pays more so...

- name: Configure K8s host from OOBE to candidate cluster member
  hosts: all
  become: yes
  remote_user: root

  tasks:
  - name: Install all pending updates
    tags:
      - oobe
      - update
    # For a clean environment; this will take a HOT second if the host just OOBE'd
    ansible.builtin.apt:
      update-cache: yes
      upgrade: yes

  # Install and Configure Docker (containerd) and CNI network components
  - name: Install Docker/Containerd dependencies
    tags:
      - oobe
      - update
    ansible.builtin.apt:
      update_cache: true
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - portmap
        - nfs-common
      state: latest

  - name: Add Docker GPG key
    # Docker is the easiest source for the containerd runtime
    tags:
      - oobe
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'
      force: true

  - name: Add Docker repo
    tags:
      - oobe
    ansible.builtin.apt_repository:
      filename: docker
      repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

  - name: Install/Update Docker
    tags:
      - oobe
      - update
    ansible.builtin.apt:
      update-cache: yes
      pkg: containerd.io
      state: latest
  
  - name: Enable br_netfilter kernel module
    # Prevents the need for a reboot and *should* make the change persistent
    tags:
      - oobe
    community.general.modprobe:
      name: br_netfilter
      state: present
  
  - name: Manually ensure load-at-boot file exists because modprobe module is broken
    tags:
      - oobe
    ansible.builtin.template:
      dest: /etc/modules-load.d/kubernetes.conf
      force: no
      mode: 0644
      owner: root
      src: module_kubernetes.conf # File only contains br_netfliter, add other drivers here if needed
  
  - name: Enable packet forwarding
    # More file shoving garbage, this one nukes /etc/sysctl.conf because net.ipv4.ip_forward=1 is commented out
    tags:
      - oobe
    ansible.builtin.template:
      dest: /etc/sysctl.conf
      force: yes  # Will probably break a working config
      mode: 0644
      owner: root
      src: sysctl.conf

  - name: Reset containerd configuration to "default"
    # More file shoving garbage, this one nukes Docker's containerd config (is how I understand it)
    tags:
      - oobe
    ansible.builtin.template:
      dest: /etc/containerd/config.toml
      force: yes  # Will probably break a working config
      mode: 0644
      owner: root
      src: containerd_config_default.conf # Created 2023-05-28; set "SystemdCgroup = true"
  
  # Install Kubernetes
  - name: Add Kubernetes APT repository
    tags:
      - oobe
    ansible.builtin.deb822_repository:
      name: kubernetes
      types: [deb]
      uris: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/"
      signed_by: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key"
      suites: [/]
      state: present
      enabled: yes

  # - name: Add Google GPG key
  #   tags:
  #     - oobe
  #   ansible.builtin.get_url:
  #     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  #     dest: /etc/apt/keyrings/kubernetes.asc
  #     mode: '0644'
  #     force: true

  # - name: Add Kubernetes repo
  #   tags:
  #     - oobe
  #   ansible.builtin.apt_repository:
  #     filename: kubernetes
  #     repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes.asc] https://apt.kubernetes.io/ kubernetes-xenial main #Gotta hard-code xenial because Kubernetes is lazy. You can replace "kubernetes-xenial" with "kubernetes-{{ ansible_distribution_release }}" once they step up their game.
  
  - name: Install/Update Kubernetes
    tags:
      - oobe
      - update
    ansible.builtin.apt:
      update-cache: yes
      pkg:
        - kubelet
        - kubeadm
        - kubectl
      state: latest

  # NetworkManager must be disabled (note: this should probably happen sooner)
  - name: Create NetworkManager directory
    tags:
      - oobe
    ansible.builtin.file:
      path: /etc/NetworkManager/conf.d
      state: directory

  - name: Disable NetworkManager for Calico's interfaces
    tags:
      - oobe
    ansible.builtin.template:
      dest: /etc/NetworkManager/conf.d/calico.conf
      force: no
      mode: 0644
      owner: root
      src: calico.conf # File only contains br_netfliter, add other drivers here if needed

  - name: Reboot host
    tags:
      - oobe
      - update
    ansible.builtin.reboot: